language: swift
matrix:
   include:
      # Test Xcode 8.3 / Swift 3.1.1
       - os: osx
         osx_image: xcode8.3
      # Test Xcode 9.2 / Swift 3.2 - 4.0
       - os: osx
         osx_image: xcode9.2

