language: generic
matrix:
   include:
      # Test Xcode 8.3 / Swift 3.1.1
       - os: osx
         osx_image: xcode8.3
      # Test Xcode 9.2 / Swift 3.2 - 4.0
       - os: osx
         osx_image: xcode9.2

script:
  # Run Unit Tests
  - swift test

  # Compile with Xcode
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd Xcode ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild clean test -scheme Bluetooth-macOS -sdk macosx -enableCodeCoverage YES ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild clean build -scheme Bluetooth-iOS ; fi